name: Atualizar linguagens no README

on:
  schedule:
    - cron: "0 4 * * MON"    # toda segunda-feira às 04:00 UTC (06:00 Maputo)
  workflow_dispatch:         # permite disparar manualmente

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checar código
        uses: actions/checkout@v4
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Instalar dependências
        run: pip install requests
      - name: Gerar seção de linguagens
        run: python scripts/update_languages.py
      - name: Commit e push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: atualiza seção de linguagens no README"
          file_pattern: README.md
